### ISSUE TITLE
View Horoscope Graphic

### ISSUE THREAD

**Issue by edde4107** [ashleycody345/tunesign#6]
Shows the user their specific horoscope (visualized data) in some graphic, and incorporates user-specific data into something that is visually appealing.

**Comment by Lachlankotarski** [comment]
We could do something like snapchat's astrological compatibility or astrological profile when you click a friend in snapchat and click their Astrological sign. So for instance if I click on Travis Scott, then I can view his astrological sign and what it means or I could view the relation between him and me.
